#!/usr/bin/env python3
"""Python commands to manage the Insound project

Example:
    Configuring CMake project in Debug mode:
    `python run config Debug`

    Build server CMake project in Debug mode:
    `python run build Debug`

    Build & Run the server in Release mode:
    `python run serve Release`


Pre-install requirements:
    - python3
    - cmake
    - ninja

"""
import os
import sys
import platform

# Name of the server project file
PROJECT_NAME: str = "insound-server"

TEST_NAME: str = "insound-tests"

# Path to the project root (this file should be located in root)
PROJECT_PATH: str = os.path.dirname(__file__)

# Path to the build folder
BUILD_PATH: str = os.path.join(PROJECT_PATH, "build")


def config(type: str = "Debug"):
    """
        Configure server CMake project and submodule libs
    """
    target_build_dir = os.path.join(BUILD_PATH, type.lower())
    result = os.system(
        f"cmake -E make_directory {target_build_dir} && "
        f"cmake -G Ninja -S {PROJECT_PATH} -B {target_build_dir} "
        f"-DCMAKE_BUILD_TYPE={type} "
        f"-DCMAKE_EXPORT_COMPILE_COMMANDS=1 "
        f"-DCROW_BUILD_TESTS=OFF -DCROW_BUILD_EXAMPLES=OFF "
    )

    if result != 0:
        exit()

    # move the current compile_commands.json to the build directory
    compile_commands_dest = os.path.join(BUILD_PATH, "compile_commands.json")
    compile_commands_orig = os.path.join(target_build_dir,
                                         "compile_commands.json")

    if not os.path.isfile(compile_commands_orig):
        print(
            f"Warning: compile_commands.json was not generated at expected "
            f"location -> \"{compile_commands_orig}\""
        )
    else:
        if os.path.isfile(compile_commands_dest):
            os.remove(compile_commands_dest)

        os.rename(compile_commands_orig, compile_commands_dest)


def build(type: str = "Debug", target: str = PROJECT_NAME):
    """
        Build a Cmake project, default is the server
    """
    config(type)
    result = os.system(
        f"cmake --build {os.path.join(BUILD_PATH, type.lower())} "
        f"--target {target}")
    if result != 0:
        exit()


def _get_binary_dir(type: str, target: str):
    """
        Get the binary directory for a project from CMake cache
    """
    cache_path = os.path.join(BUILD_PATH, type.lower(), "CMakeCache.txt")
    if not os.path.exists(cache_path):
        print("Error, could not find CMake cache at expected location: " +
              cache_path)
        exit()
    file = open(cache_path)

    var_name = target + "_BINARY_DIR"
    lines = file.readlines()
    for line in lines:
        if line.startswith(var_name):
            return line.rstrip().split("=")[1]

    return os.path.join(BUILD_PATH, type.lower())


def kill_server():
    """
        Kill the server if it's currently running.
        Only available on macOS and Linux
    """
    if os.name != "nt":
        os.system(f"if pgrep {PROJECT_NAME}; then pkill {PROJECT_NAME}; fi")
    else:
        print("Windows kill_server() is unimplemented")


def memcheck(type: str = "Debug", target: str = PROJECT_NAME):
    """
        On macOS, use `leaks` to detect memory leaks in the program
    """
    if platform.system() != "Darwin":
        print("Sorry, memcheck only supports macOS via leaks")
    build(type, target)
    result = os.system("export MallocStackLogging")
    if result != 0:
        exit()

    exec_path = os.path.join(_get_binary_dir(type, target), target)

    if target == PROJECT_NAME:
        kill_server()

    result = os.system(f"leaks --list -q --atExit -- {exec_path}")


def serve(type: str = "Debug"):
    """
        Build & run the server
    """
    kill_server()
    build(type, PROJECT_NAME)
    os.system(f"{os.path.join(BUILD_PATH, type.lower(), PROJECT_NAME)}")


def test(type: str = "Debug"):
    """
        Build & run the tests
    """
    build(type, TEST_NAME)
    target = os.path.join(BUILD_PATH, type.lower(), 'tests', TEST_NAME)
    os.system(target)


def help():
    """
        Display the help menu
    """
    print(
        "\n"
        "====== Insound build helper script ===============================\n"
        "\n"
        "       Build script for project management. Please make sure that \n"
        "       Python 3, CMake and Ninja are installed on your system in \n"
        "       order to use the build system.\n"
        "\n"
        "COMMANDS\n"
        "\n"
        "  config     <build_type>\n"
        "\n"
        "      configures build scripts\n"
        "\n"
        "      available build types: \n"
        "      - Release\n"
        "      - Debug (default)\n"
        "      - RelWithDebInfo\n"
        "      - MinSizeRel\n"
        "\n"
        "\n"
        "  build      <build_type> <target_name>\n"
        "\n"
        "      builds a cmake target\n"
        "\n"
        "      available target names: \n"
        "      - insound-server (default)\n"
        "      - insound-tests\n"
        "\n"
        "  serve      <build_type>\n"
        "\n"
        "      configures, builds, and runs insound-server\n"
        "\n"
        "  test       <build_type>\n"
        "\n"
        "      configures, builds, and runs insound-tests\n"
        "\n"
    )


def main(argc: int, argv: list[str]):
    this = sys.modules[__name__]

    # There should be a command
    if argc < 2:
        help()
        exit()

    # Get the command, and run it if it is available
    try:
        command = getattr(this, argv[1])
    except AttributeError as e:
        print(f"Could not find command \"{argv[1]}\"")
        help()
        exit()

    if command is not None and callable(command):
        # Pass args if any
        if argc > 2:
            command(*argv[2:])
        else:
            command()
    else:
        help()


if __name__ == "__main__":
    main(len(sys.argv), sys.argv)
